### ISSUE TITLE
Why jumper J_DIO5 is open?

### ISSUE THREAD

**Issue by guillemonzo** [gonzalocasas/arduino-uno-dragino-lorawan#3]
Hi, 

I'm starting with lorawan and I've purchased a Dragino LoRa Shield (v1.4). My goal is to use it as node and connect it to TTN.

I've tested the ``hello-world.ino`` example but I'm not sure if I'm not reaching the nearest gateway (I'm around 1km far away) or it's just not working. On serial monitor I can only see this every 60 seconds, but the node is not displayed on the TTN console:

``Sending uplink packet...``
``EV_TXCOMPLETE (includes waiting for RX windows)``

I've tried with the jumper J_DIO5 open and close and I'm using MSB for the network and application keys, but the node is still not seen on the TTN console.

Why should jumper J_DIO5 be open?

I'll try to get closer to the gateway and see if that's the problem.

**Comment by gonzalocasas** [comment]
I'm not sure, this code was written long ago for the 1.3 version of the shield, I don't know if the recommendations still apply.

**Comment by guillemonzo** [comment]
I finally could connect the Dragino to TTN, the problem was I didn't reach the gateway. I got closer and it connected with the jumper closed, so probably is not needed to open it for the 1.4 version.
